# Generated by Django 5.0.6 on 2024-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('artist', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
