# Generated by Django 5.0.6 on 2024-06-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='id_artist',
            field=models.CharField(default='', max_length=200),
        ),
    ]
