# Generated by Django 5.0.6 on 2024-06-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_albums_id_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='id_album',
            field=models.CharField(default='', max_length=200),
        ),
    ]
