# Generated by Django 5.0.6 on 2024-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('id_album', models.IntegerField(blank=True, null=True)),
                ('id_artist', models.IntegerField(blank=True, null=True)),
                ('id_track', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
