# Generated by Django 5.0.6 on 2024-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='spotify_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
