# Generated by Django 5.0.6 on 2024-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_tracks_spotify_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
