# Generated by Django 5.0.6 on 2024-06-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_tracks_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='preview_url',
        ),
    ]
