# Generated by Django 5.0.6 on 2024-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='spotify_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
